apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:KjQAXYeBkmZ2hYSCBNL3srJXlGu1G52v,iv:9ZskoL/LdHY7a+IPsJFh87XIcULyeo1FhNjdQQvrnxc=,tag:H51IxaXoukCJN1CR0q8aBg==,type:str]
    client_secret: ENC[AES256_GCM,data:emP/fNIcEr7qhzfNCDS1sXtgS12fci6bLaUibKz3D6l9qjhJ6QC8SQhfeziii19dvDH902YnQ9AsvFDFyCyBF7Ezt0mxzqeTPDlD3356bvgBqI38sqyMPg==,iv:O3lxdabpKMk0U/rtKU6EJT54DXTm5Kk/FTXTJOZoAvE=,tag:r7mE5RhWESfV+6wjcS6CLw==,type:str]
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU0FiSmZiUGNxb3N2ZGI1
            NlpidWh5cHJ0UmE3TVJMa0tnUUJZN3JCdXprCjM1b2dwTkxtSFp1akUzNTdxNEVT
            Q1FYTkExMkkyZm5GZXlpemt5dGRPRTAKLS0tIEJuZlZHSndvZnBiejdIREFPck5t
            ZE5TZFl3QlYvTDVWamd2dHlYRHFMeGsKV3lqsRBvwh1ys9C6IgbAWK6TlbDGCtWT
            hzB0DHlCOrwAgUnAODiqxkYLzVhr/uIrttf7MrBJxBkgHRPoeSP7Rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100gaz55vrmymru2n7a6tfp27m4706wu88scgp3xemlerr9f6lffsrflhw0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T08:23:19Z"
    mac: ENC[AES256_GCM,data:2cGiqQPFGaHXn+Id+PCGNWVwYK4yufS3mibIWYAQCUH+T1kFq/KRzHEE0gvtZpArmXMChovienEkBstYSTVQN6Dc3aKR7RQZxYic5ehvoHEXs9WqByBAHj0epz9Xl2HAkC1dz2mprJlZOoeeblhhaADr59CD3zzeAtWY4XcU5x8=,iv:AX+yBuV1xupMX8ATEzC33DqKR2iDyUMyLNIgD/DpQ/s=,tag:UO03pZ1mpBHb3obMVsHe2g==,type:str]
    version: 3.13.1
