apiVersion: v1
data:
    key: ENC[AES256_GCM,data:M2CdIKvfYwo=,iv:ZnGLV8KzdfawDTP/DBp+EN3vw8MCPf1TZlBMd7QhnKs=,tag:f61OeFHMMqyCHS4Yb02OYA==,type:str]
kind: Secret
metadata:
    name: sops-test
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSnB0WHI5MGVzdE9ZNFhX
            U0tzbEFxMDY1WlVpNituV3M3cWRiR2J1Y1RVCiswSWtJUUxTVG9HL2dJYm9NZXkx
            SWVRdmJGTDFWdTNTTnhnVjEwcDhOVWsKLS0tIEprT0NRVzg3YkpQUHZXTm9UblVh
            bDd0MFVONjF3N3MrY1k4Q3pyVStuWmsKJRGNH+b6d0wN/DkyVV5t+e1bbU7Flt50
            zo82PCxVeEyZN3qcQbMOD+O7njoXHPTAfFGrJvhKRvztEZoAODTnAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100gaz55vrmymru2n7a6tfp27m4706wu88scgp3xemlerr9f6lffsrflhw0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T05:17:05Z"
    mac: ENC[AES256_GCM,data:XQxIRodaB9PGy8yC0Nmu/q4wcsEYJpRPuIntk5SAF1aBptVxWz99R+hJ0YoL/fWhvqfY/p94gbxRfuyVTUMMn0iZq75QTQjB9wOdCWCu9WdBGVTApgUAYR7MxRD5nrWeu/VDYTItNs/e/89nEQ+pqzsOBHtZWC+GszEA1WTxQYI=,iv:ODdxlLifHLwOdVVtqvxFhsxyMw2oiTk25NmlJc4HdFE=,tag:fhByGbsx+Zl91yU84KgTxw==,type:str]
    version: 3.13.1
