apiVersion: v1
data:
    telegram_bot_token: ENC[AES256_GCM,data:DuQMO+PKCDzW+ud8yyo58BTEoU6bM8Ch9Jop6W63rCkkhyeZff4WtgJVY+AR6mF8rcnkGdjN2E2Ni53ZrY7m6A==,iv:JK4uYo9v8DnmY87RuDhlNlv4iejvhZBt3UujQTgFJiw=,tag:QTjvyazVJtvvZN7is+2/vw==,type:str]
    telegram_chat_id: ENC[AES256_GCM,data:cQWTQe8JFlekKAxFbSxOCg==,iv:QJVi76fMRhnFooxQFQzRFxkeuHqiz2sB/x4GKQXaccc=,tag:YFSL4htDmDAWPjQoePSgfg==,type:str]
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZU5jVEM2U2w3RlNHT29Y
            SzN4S0dBN3RJdjFHZ05FZ3VmMzVld3Q4Y0I0CmVOK1NzNTArbmFjaFc5TTNMMzdj
            NGx0YzNac1ZkTS9vQWt5UFpVSi9IamcKLS0tIFRrTlNIMUcvM3ltZzRxRzNFZ3lQ
            R2lWeWRXTitveGVlSERjREg1YWF5d3MKd/DY0SIbBAvLRPyTX0LHzXOz7YR3aA9o
            oeDZ4tBn6Bz4/vYE5AkDiyTG4p6nOb+xme1sotTbpAcn5RsO1nCYTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age100gaz55vrmymru2n7a6tfp27m4706wu88scgp3xemlerr9f6lffsrflhw0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T08:03:27Z"
    mac: ENC[AES256_GCM,data:89etdFrzS7VoUo2dzhq/kZWoFhYP90rMke8riqbhDZ/yDo5w5+vJlMUpcysyWwm75Nlz8e7dUrO2zRmVzj71TbxfoVBjYDWsBhuGAfsQZs5q+Yb+5DdDduH+eOn1kSVAQ2/AsXSEwRlSY+WcOJp9+7wLU4BWaJ1fkcSuyTTwk0A=,iv:JCJWHQ+4oQ51JK5oUh2PscSdSxlwB7pun+PuSuoDMJw=,tag:7Xgfp+eHiecMI0xiS9/DgA==,type:str]
    version: 3.13.1
